"""Initial schema with all models

Revision ID: 87784065e333
Revises: 
Create Date: 2025-12-07 02:36:05.414430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87784065e333'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('personas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('baseline_age', sa.Integer(), nullable=False),
    sa.Column('baseline_gender', sa.String(), nullable=True),
    sa.Column('baseline_background', sa.Text(), nullable=True),
    sa.Column('current_personality', sa.JSON(), nullable=False),
    sa.Column('current_attachment_style', sa.String(), nullable=False),
    sa.Column('current_trauma_markers', sa.JSON(), nullable=False),
    sa.Column('current_age', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('share_token', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_token')
    )
    op.create_table('experiences',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('persona_id', sa.String(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('age_at_event', sa.Integer(), nullable=False),
    sa.Column('user_description', sa.Text(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('severity', sa.Integer(), nullable=True),
    sa.Column('support_available', sa.Boolean(), nullable=True),
    sa.Column('immediate_effects', sa.JSON(), nullable=True),
    sa.Column('long_term_patterns', sa.JSON(), nullable=True),
    sa.Column('cross_experience_triggers', sa.JSON(), nullable=True),
    sa.Column('coping_mechanisms', sa.JSON(), nullable=True),
    sa.Column('worldview_shifts', sa.JSON(), nullable=True),
    sa.Column('symptoms_developed', sa.JSON(), nullable=True),
    sa.Column('symptom_severity', sa.JSON(), nullable=True),
    sa.Column('recommended_therapies', sa.JSON(), nullable=True),
    sa.Column('ai_reasoning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interventions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('persona_id', sa.String(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('age_at_intervention', sa.Integer(), nullable=False),
    sa.Column('therapy_type', sa.String(), nullable=False),
    sa.Column('duration', sa.String(), nullable=False),
    sa.Column('intensity', sa.String(), nullable=False),
    sa.Column('user_notes', sa.Text(), nullable=True),
    sa.Column('target_symptoms', sa.JSON(), nullable=True),
    sa.Column('actual_symptoms_targeted', sa.JSON(), nullable=True),
    sa.Column('efficacy_match', sa.Float(), nullable=True),
    sa.Column('immediate_effects', sa.JSON(), nullable=True),
    sa.Column('sustained_effects', sa.JSON(), nullable=True),
    sa.Column('limitations', sa.JSON(), nullable=True),
    sa.Column('symptom_changes', sa.JSON(), nullable=True),
    sa.Column('personality_changes', sa.JSON(), nullable=True),
    sa.Column('coping_skills_gained', sa.JSON(), nullable=True),
    sa.Column('ai_reasoning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personality_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('persona_id', sa.String(), nullable=False),
    sa.Column('experience_id', sa.String(), nullable=True),
    sa.Column('intervention_id', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('personality_profile', sa.JSON(), nullable=False),
    sa.Column('attachment_style', sa.String(), nullable=False),
    sa.Column('trauma_markers', sa.JSON(), nullable=False),
    sa.Column('symptom_severity', sa.JSON(), nullable=False),
    sa.Column('narrative_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ),
    sa.ForeignKeyConstraint(['intervention_id'], ['interventions.id'], ),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personality_snapshots')
    op.drop_table('interventions')
    op.drop_table('experiences')
    op.drop_table('personas')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
